name: Say hello

on: 
  push:
    branches:
      - main
 
jobs: 
  hello_world: 
    runs_on: ubuntu-18.04
    steps: 
      - name: Echo the message
        run:  |
          echo !Hola Gabi!"

        